### ISSUE TITLE
Errors during merge: Use of uninitialized value 

### ISSUE THREAD

**Issue by copyme** [brunopostle/ifcmerge#4]
I am not sure if the tool was designed for such a use, but I tried to merge three locally existing IFC files. Probably, it is not an intended use case. In any case, I got these errors.

```Use of uninitialized value $base_class in string ne at ./ifcmerge line 102.
Use of uninitialized value $local_class in string ne at ./ifcmerge line 102.
Use of uninitialized value $text in pattern match (m//) at ./ifcmerge line 340.
Use of uninitialized value $text in pattern match (m//) at ./ifcmerge line 340.
Use of uninitialized value $base_class in string ne at ./ifcmerge line 102.
Use of uninitialized value $local_class in string ne at ./ifcmerge line 102.
Use of uninitialized value $text in pattern match (m//) at ./ifcmerge line 340.
Use of uninitialized value $text in pattern match (m//) at ./ifcmerge line 340.
```

**Comment by brunopostle** [comment]
Thanks, can you share an example that shows this error?

This sort of error could be caused by multiline comments, do your files
have comments like this?:

  /* A comment that
  continues on another line */

**Comment by copyme** [comment]
Hi! @brunopostle let me check if I can share the IFC files with you.

**Comment by copyme** [comment]
Also, sorry for the late reply. I overlooked your answer.
