### ISSUE TITLE
Zotero Connector does not recognise CITATION.cff

### ISSUE THREAD

**Issue by Martin15135215** [brunopostle/ifcmerge#6]
I then validated the CITATION.cff and found that `type` has an invalid value:

https://github.com/brunopostle/ifcmerge/blob/74226d6c97afff3c02baf07f56c848595efd8e90/CITATION.cff#L8

`type` in this top position can only be `software` or `dataset`, see https://github.com/citation-file-format/citation-file-format/blob/1.2.0/schema-guide.md#type

However, for example in [credit-redirection](https://github.com/citation-file-format/citation-file-format/blob/1.2.0/schema-guide.md#credit-redirection) block, you can use `type` with the value `article`.

Nonetheless, I am uncertain whether this approach would resolve my Zotero Connector issue. Therefore, I would like to inquire whether it is feasible to incorporate a bib file that I can import into Zotero?

**Comment by brunopostle** [comment]
Thanks, it now validates. The CFF file is now 'for' the ifcmerge tool and a 'preferred-citation' section points to the Whitepaper. I've also added a basic BIB file for the Whitepaper.

**Comment by Martin15135215** [comment]
Thanks a lot!
