### ISSUE TITLE
Aren't we now using the BCF instead of mail?

### ISSUE THREAD

**Issue by Martin15135215** [brunopostle/ifcmerge#7]
Thanks for the white paper! It was a pleasant read.

Just a little remake to this example! I am not sure how far the AEC industry got in two years since the publication of this white paper, however do they not use BCF instead of mail?

https://github.com/brunopostle/ifcmerge/blob/14807c48506c11f0ccb22b8e625a254ed436202b/docs/whitepaper.rst?plain=1#L34

**Comment by brunopostle** [comment]
Maybe the industry has moved on, or some parts of it have. 

I can say that as part of my work I often have to search the entire correspondence of AEC projects (admittedly these are by definition older projects so not fully representative). In terabytes of data grabbed from various hard disks, file servers and CDE systems, produced by thousands of consultants and contractors from all regions, I have never once seen a BCF file.

**Comment by Martin15135215** [comment]
Thanks for the input. I'm still a student, so I don't know how far the industry has come yet.

**Comment by brunopostle** [comment]
I'm sure somebody is making a lot of use of BCF, just not in the bit of the industry I see.

For communication, people are circulating huge Excel lists of items with additional columns for everyone to comment, or pasting screenshots into Word.

**Comment by Martin15135215** [comment]
I see, I hope when I am working, I don't have to fiddle with huge Excel file…

I would like to mention that I opened this [discussion](https://github.com/IfcOpenShell/IfcOpenShell/discussions/4215) in IfcOpenShell, to know how IfcOpenShell behaves in certain edge cases, to see how well the three technical requirements for using git with ifc are held.
